'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import Script from 'next/script';
import { useRouter } from 'next/navigation';
import type { CartResponse, UserProfile } from '@seethapaati/contracts';
import { fetchApi, ApiClientError } from '../../lib/api-client';

declare global { interface Window { Razorpay?: new (options: Record<string, unknown>) => { open: () => void }; } }
type Address = { id?: string; fullName:string; phone:string; addressLine1:string; addressLine2?:string; city:string; state:string; postalCode:string; country:string; isDefault:boolean };
const emptyAddress: Address = { fullName:'', phone:'', addressLine1:'', addressLine2:'', city:'', state:'', postalCode:'', country:'IN', isDefault:true };

export default function CheckoutPage() {
  const router=useRouter();
  const [cart,setCart]=useState<CartResponse|null>(null); const [profile,setProfile]=useState<UserProfile|null>(null); const [addresses,setAddresses]=useState<Address[]>([]); const [address,setAddress]=useState<Address>(emptyAddress); const [stateCode,setStateCode]=useState(''); const [coupon,setCoupon]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [paying,setPaying]=useState(false); const [savingAddress,setSavingAddress]=useState(false);
  useEffect(()=>{Promise.all([fetchApi<CartResponse>('/cart'),fetchApi<UserProfile>('/users/me'),fetchApi<Address[]>('/users/me/addresses')]).then(([nextCart,nextProfile,nextAddresses])=>{setCart(nextCart);setProfile(nextProfile);setAddresses(nextAddresses);const preferred=nextAddresses.find(a=>a.isDefault)??nextAddresses[0];if(preferred)setAddress(preferred);else setAddress(a=>({...a,fullName:nextProfile.fullName,phone:nextProfile.phone??''}));}).catch(err=>{if(err instanceof ApiClientError&&['UNAUTHORIZED','USER_NOT_FOUND'].includes(err.code))router.replace('/account/login?next=/checkout');else setError(err instanceof Error?err.message:'Unable to load checkout')}).finally(()=>setLoading(false));},[router]);
  function setField<K extends keyof Address>(key:K,value:Address[K]){setAddress(a=>({...a,[key]:value}));}
  async function saveAddress(){setSavingAddress(true);try{const saved=await fetchApi<Address>('/users/me/addresses',{method:'POST',body:JSON.stringify({...address,isDefault:addresses.length===0})});setAddresses(a=>[...a,saved]);setAddress(saved);}catch(err){setError(err instanceof Error?err.message:'Unable to save address')}finally{setSavingAddress(false)}}
  async function submit(event:FormEvent){event.preventDefault();if(!cart||!profile||cart.items.length===0)return;setError('');setPaying(true);try{const shippingAddress={...address,stateCode,country:'IN'};if(!shippingAddress.fullName||!shippingAddress.phone||!shippingAddress.addressLine1||!shippingAddress.city||!shippingAddress.state||!shippingAddress.postalCode||!/^[0-9]{2}$/.test(stateCode))throw new Error('Complete the shipping address and two-digit GST state code.');const intent=await fetchApi<{orderId:string;orderNumber:string;amountCents:number;currency:string;gateway:string;gatewayOrderId:string;gatewayKeyId:string}>('/checkout/intent',{method:'POST',body:JSON.stringify({cartId:cart.cartId,shippingAddress,couponCode:coupon.trim()||undefined,idempotencyKey:crypto.randomUUID()})});if(intent.gateway!=='RAZORPAY')throw new Error('Unsupported payment gateway');if(!window.Razorpay)throw new Error('Payment checkout is still loading. Please try again.');const payment=new window.Razorpay({key:intent.gatewayKeyId,amount:intent.amountCents,currency:intent.currency,name:'SEETHAPAATI',order_id:intent.gatewayOrderId,prefill:{name:shippingAddress.fullName,email:profile.email,contact:shippingAddress.phone},handler:async(response:Record<string,string>)=>{try{await fetchApi('/checkout/verify',{method:'POST',body:JSON.stringify({orderId:intent.orderId,razorpay_payment_id:response.razorpay_payment_id,razorpay_order_id:response.razorpay_order_id,razorpay_signature:response.razorpay_signature})});router.replace('/orders/'+intent.orderId+'/confirmation')}catch(err){setError(err instanceof Error?err.message:'Payment verification failed');setPaying(false)}},modal:{ondismiss:()=>setPaying(false)}});payment.open();}catch(err){setError(err instanceof Error?err.message:'Unable to start payment');setPaying(false)}}
  if(loading)return <><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive"/><main className="editorial-page mx-auto max-w-6xl px-6 py-24 md:py-32"><div className="animate-pulse space-y-8"><div className="h-12 w-64 bg-[#ECE8E0]"/><div className="grid gap-10 md:grid-cols-[1fr_340px]"><div className="h-80 bg-[#ECE8E0]"/><div className="h-64 bg-[#ECE8E0]"/></div></div></main></>;
  if(error&&!cart)return <><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive"/><main className="editorial-page mx-auto max-w-3xl px-6 py-28 text-center"><p className="eyebrow justify-center"><span className="eyebrow-dot"/> Secure checkout</p><h1 className="mt-5 font-serif text-5xl">Checkout unavailable</h1><p className="mt-4 text-sm text-red-700">{error}</p></main></>;
  if(!cart||cart.items.length===0)return <><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive"/><main className="editorial-page mx-auto max-w-3xl px-6 py-28 text-center"><p className="eyebrow justify-center"><span className="eyebrow-dot"/> Secure checkout</p><h1 className="mt-5 font-serif text-5xl md:text-6xl">Your bag is empty.</h1><p className="mt-4 text-sm text-[#181513]/55">Add something to your bag before continuing.</p><Link href="/shop" className="mt-7 inline-block text-[10px] uppercase tracking-[0.18em] text-[#A66B18] underline underline-offset-4">Return to shop →</Link></main></>;
  return <><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive"/><main className="editorial-page mx-auto max-w-[1280px] px-6 pb-20 pt-12 md:px-10 md:pb-28 md:pt-20">
    <header className="border-b border-[#E3DFD7] pb-8"><p className="eyebrow"><span className="eyebrow-dot"/> Secure checkout</p><div className="mt-4 flex flex-wrap items-end justify-between gap-5"><h1 className="font-serif text-5xl tracking-[-0.05em] md:text-7xl">Delivery details.</h1><Link href="/cart" className="text-[10px] uppercase tracking-[0.17em] text-[#A66B18] underline underline-offset-4">Back to bag</Link></div><p className="mt-5 max-w-2xl text-sm leading-7 text-[#181513]/60">Your final price, tax, stock and shipping are recalculated by the commerce API when the payment order is created.</p></header>
    <form onSubmit={submit} className="mt-10 grid gap-12 md:mt-14 md:grid-cols-[1fr_340px] lg:gap-20">
      <section className="space-y-9">
        {addresses.length>0&&<div><p className="text-[10px] uppercase tracking-[0.2em] text-[#181513]/50">Saved addresses</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{addresses.map(a=><button type="button" key={a.id} onClick={()=>setAddress(a)} className={'w-full border p-5 text-left text-sm transition-colors '+(address.id===a.id?'border-[#181513] bg-white/35':'border-[#E3DFD7] hover:border-[#B8860B]')}><span className="font-medium">{a.fullName}</span>{a.isDefault&&<span className="ml-2 text-[9px] uppercase tracking-[0.12em] text-[#A66B18]">Default</span>}<br/><span className="text-[#181513]/60">{a.addressLine1}, {a.city}, {a.state} {a.postalCode}</span></button>)}</div></div>}
        <div className="border-t border-[#181513] pt-7"><p className="text-[10px] uppercase tracking-[0.2em] text-[#181513]/50">Delivery address</p><div className="mt-6 grid gap-6 sm:grid-cols-2">{([['fullName','Full name'],['phone','Phone'],['addressLine1','Address line 1'],['addressLine2','Address line 2'],['city','City'],['state','State'],['postalCode','Postal code']] as const).map(([key,label])=><label key={key} className="block text-[10px] uppercase tracking-[0.14em]">{label}<input required={key!=='addressLine2'} value={String(address[key]??'')} onChange={e=>setField(key,e.target.value)} className="mt-2 w-full border-b border-[#181513]/25 bg-transparent py-3 outline-none transition-colors focus:border-[#B8860B]"/></label>)}<label className="block text-[10px] uppercase tracking-[0.14em]">GST state code<input required value={stateCode} maxLength={2} inputMode="numeric" pattern="[0-9]{2}" placeholder="e.g. 33" onChange={e=>setStateCode(e.target.value.replace(/\D/g,'').slice(0,2))} className="mt-2 w-full border-b border-[#181513]/25 bg-transparent py-3 outline-none transition-colors focus:border-[#B8860B]"/></label></div></div>
        <button type="button" disabled={savingAddress} onClick={()=>saveAddress()} className="text-[10px] uppercase tracking-[0.16em] text-[#A66B18] underline underline-offset-4 disabled:opacity-50">{savingAddress?'Saving address…':'Save this address to my account'}</button>
        <div className="border-t border-[#E3DFD7] pt-7"><label className="block text-[10px] uppercase tracking-[0.14em]">Coupon code <span className="text-[#181513]/35">(optional)</span><input value={coupon} onChange={e=>setCoupon(e.target.value)} className="mt-2 w-full max-w-xs border-b border-[#181513]/25 bg-transparent py-3 outline-none transition-colors focus:border-[#B8860B]"/></label></div>
        {error&&<p role="alert" className="border-l-2 border-red-700 px-4 py-2 text-sm text-red-700">{error}</p>}
      </section>
      <aside className="h-fit border-t border-[#181513] pt-6 md:sticky md:top-10"><p className="text-[10px] uppercase tracking-[0.2em] text-[#181513]/50">Order summary</p><div className="mt-6 space-y-3 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>₹{(cart.pricing.subtotalCents/100).toLocaleString('en-IN')}</span></div><div className="flex justify-between"><span>Tax</span><span>₹{(cart.pricing.taxCents/100).toLocaleString('en-IN')}</span></div><div className="flex justify-between"><span>Shipping</span><span>₹{(cart.pricing.shippingCents/100).toLocaleString('en-IN')}</span></div>{cart.pricing.discountCents>0&&<div className="flex justify-between"><span>Discount</span><span>-₹{(cart.pricing.discountCents/100).toLocaleString('en-IN')}</span></div>}</div><div className="mt-6 flex justify-between border-t border-[#E3DFD7] pt-5 font-serif text-2xl"><span>Total</span><span>₹{(cart.pricing.grandTotalCents/100).toLocaleString('en-IN')}</span></div><p className="mt-3 text-[10px] leading-5 text-[#181513]/45">Final totals are confirmed server-side before payment.</p><button disabled={paying} className="mt-7 w-full bg-[#181513] px-6 py-4 text-[10px] uppercase tracking-[0.18em] text-[#F7F5F0] transition-colors hover:bg-[#A66B18] disabled:opacity-50">{paying?'Opening payment…':'Continue to payment'}</button><p className="mt-4 text-center text-[9px] uppercase tracking-[0.14em] text-[#181513]/35">Secure payment via Razorpay</p></aside>
    </form>
  </main></>;
}